################################################################
#
# Pipeline.yml file for rmats permutations pipeline.
#
# 
#
################################################################

database:
   name: "csvdb"


gtf_dir: "/fastdata/bof20am/l4project/rmats_tcga/TCGA-agg-agg.filtered.gtf"

rmats:
  threads: 2
  mem: 16G

data:
  rx: /(?P<s_name>.+)-T(?P<s_time>.+)-(?P<s_rep>.+)\.star\.bam
